# Generated by Django 4.1.4 on 2023-01-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='total_qty',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
