# Generated by Django 4.1.4 on 2023-01-30 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0002_demand_total_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=50)),
                ('number', models.CharField(blank=True, max_length=8, null=True)),
                ('complement', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(max_length=30)),
                ('cep', models.CharField(max_length=8)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demands.demand')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
