# Generated by Django 4.1.4 on 2023-01-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0003_addressdemand'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='total_w_shipping',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
