# Generated by Django 4.1.4 on 2023-01-31 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0004_demand_total_w_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='shipping_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
