# Generated by Django 4.1.4 on 2023-03-06 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0005_demand_shipping_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='creation_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
