# Generated by Django 4.1.4 on 2022-12-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('summary', models.TextField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_img/%Y/%m/%d')),
                ('slug', models.SlugField(unique=True)),
                ('mrkt_price', models.FloatField(verbose_name='marketing price')),
                ('promo_mrkt_price', models.FloatField(default=0, verbose_name='promotional marketing price')),
                ('var_type', models.CharField(choices=[('V', 'Variable'), ('S', 'Simple')], default='V', max_length=1)),
            ],
        ),
    ]
