# Generated by Django 4.1.4 on 2023-02-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_variation_name_alter_variation_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('T', 'Technology'), ('C', 'Clothes'), ('F', 'Furniture')], default='T', max_length=1),
        ),
    ]
