# Generated by Django 4.1.4 on 2023-03-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='product_img/%Y/%m/%d'),
        ),
    ]
